name:                opto
version:             0.1.0.0
github:              "mstksg/opto"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.6

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            General-purpose performant numeric optimization library
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mstksg/opto#readme>

dependencies:
- backprop >= 0.2
- base >= 4.7 && < 5
- data-default
- deepseq
- hmatrix
- mwc-random
- primitive
- reflection
- transformers
- vector >= 0.12.0.2

ghc-options:
- -Wall
- -Wredundant-constraints
- -Werror=incomplete-patterns
- -Wcompat

library:
  source-dirs: src
  dependencies:
  - conduit >= 1.3.0
  - constraints
  - finite-typelits
  - ghc-typelits-knownnat
  - hmatrix-vector-sized >= 0.1.2
  - invariant
  - mono-traversable
  - mtl
  - one-liner
  - semigroupoids
  - stm
  - stm-chans
  - stm-conduit
  - time
  - unliftio
  - unliftio-core
  - vector-sized >= 1.0
  - vinyl

executables:
  opto-neural:
    main:                opto-neural.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filepath
    - hmatrix-backprop >= 0.1.3
    - lens
    - mnist-idx
    - one-liner-instances
    - opto
    - optparse-applicative

# tests:
#   opto-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - opto
